### PR TITLE
Consider calculated project properties

### PR DESCRIPTION
**Pull request by Vampire**
## Description
Having the following in a project with the project-specific token set did not work as the plugin took a snapshot of the properties
of the root project when the extension was created instead of accessing the properties live when needed.

```gradle
ext {
    it.'github.token' = project.findProperty('my-project.github.token') ?: project.findProperty('github.token')
}
```

With this change it works fine either way.

## Changes

![IMPROVE] lazy property resolution in `DefaultGithubPluginExtension`

[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"

### CODE REVIEW

**Comment by Vampire** [comment]
What is the build error?

**Comment by Larusso** [comment]
Uh looks like 10km Test fails. Let me check when I’m in the office on a proper computer.

**Comment by Larusso** [comment]
Ah from your changes this makes a lot of sense. I passed a map to make test life easier. But I see that this breaks lazy evaluation. Will check which tests need to be updated.

**Comment by Larusso** [comment]
Ok it's only the gradle 5 deprecation warnings. I had no time yet to make this plugin compatible with gradle 5. I disabled these warnings on `master`. I quick rebase should fix this PR.

**Review by Larusso — APPROVED** [review]

**Comment by Vampire** [comment]
Ok, update is pushed

**Comment by Larusso** [comment]
Ok. I forgot that jenkins already merges before running the tests. I'll will wait for this last commit and do a release afterwards.

Thanks!

**Comment by Vampire** [comment]
Ah, I already wondered why the checks were green already.
But if he rebuilds PRs pre-merged when the base-branch updates, this makes sense of course.

**Comment by Larusso** [comment]
released in [`1.2.0`](https://github.com/wooga/atlas-github/releases/tag/v1.2.0)

**Pull request merged**
